### ISSUE TITLE
Open new files in tabs doesn't work

### ISSUE THREAD

**Issue by gabey14** [flathub/org.kde.okular#202] opened 2022-09-19 13:03 UTC
The checkbox **open new files in tabs** is **checked** but still it doesn't open in tabs also  **switch to existing tab if file is already open** also doesn't work.

**Comment by Erick555** [comment] 2022-09-19 14:52
Duplicate of https://github.com/flathub/org.kde.okular/issues/36

**Closed** 2022-09-19 14:57 UTC
